### ISSUE TITLE
Swipe move inconsistent behaviour ON *mac OS* + *Forge*

### ISSUE THREAD

**Issue by IdaFoll** [blackd/Inventory-Profiles#150] opened 2022-07-07 09:51 UTC
When I try to shift left click items in and out of chests, items don’t react like they should. Sometimes two item stacks are moved together, sometimes items are just replaced by different items and other weird stuff. I’m playing in Minecraft 1.18.2, I’ve tried every single version of the mod with no difference. The problem is there even when I only have that one mod installed. It makes the game unplayable, I’ve list a bunch of stuff not realizing two stacks if completely different items were moved.
English is not my first language, and I don’t know if this is the right way to report the issue, I can add more info if needed.

**Comment by blackd** [comment] 2022-07-07 09:53
which modloader do you use?
what other mods do you have installed?

**Comment by blackd** [comment] 2022-07-07 09:55
The best way to show me the problem is to make a video when it happens

**Comment by IdaFoll** [comment] 2022-07-07 09:55
For testing purposes I only have the inventory profiles next mod installed. Took a while to figure out which mod was creating the issue. I use curseforge modloader.

**Comment by IdaFoll** [comment] 2022-07-07 09:57
I'll try to get a video taken!

**Comment by blackd** [comment] 2022-07-07 10:12
If you want you can join out discord server https://discord.gg/23YCxmveUM so we can have real time communication

**Comment by IdaFoll** [comment] 2022-07-07 10:22
I have joined the discord now, I have a video I can send too

**Comment by blackd** [comment] 2022-07-07 10:28
you can either send it here or discord

**Comment by IdaFoll** [comment] 2022-07-07 10:29
I can't seem to send it here, who do I send it to on discord?☺️

**Comment by blackd** [comment] 2023-01-19 10:52
Hi @IdaFoll, @hinls1007

If you are still interested can you please update IPN to the latest version  and try with the appropriate version of libIPN from here (download it rename it from .zip to .jar and move it into your mods folder, also remove the old version):


[libIPN-forge-1.16-2.0.2-SNAPSHOT.zip](https://github.com/blackd/Inventory-Profiles/files/10455971/libIPN-forge-1.16-2.0.2-SNAPSHOT.zip)
[libIPN-forge-1.18.2-2.0.2-SNAPSHOT.zip](https://github.com/blackd/Inventory-Profiles/files/10455972/libIPN-forge-1.18.2-2.0.2-SNAPSHOT.zip)
[libIPN-forge-1.19-2.0.2-SNAPSHOT.zip](https://github.com/blackd/Inventory-Profiles/files/10455973/libIPN-forge-1.19-2.0.2-SNAPSHOT.zip)
[libIPN-forge-1.19.3-2.0.2-SNAPSHOT.zip](https://github.com/blackd/Inventory-Profiles/files/10455974/libIPN-forge-1.19.3-2.0.2-SNAPSHOT.zip)

**Comment by IdaFoll** [comment] 2023-01-27 09:28
Hi! Just tried it, and now it works!
At least with 1.18.2 and the setup that I have.
Also, locked slots works now. The only reason I noticed your comment is that I noticed I couldn't lock slots and I wanted to see if there was a fix. Hell of a coincidence.

**Comment by blackd** [comment] 2023-01-29 13:47
FIXED in v1.9.2

**Closed as completed by blackd** 2023-01-29 13:47 UTC
