### ISSUE TITLE
Unequal before and after item counts

### ISSUE THREAD

**Issue by Colluttorio** [blackd/Inventory-Profiles#411] opened 2024-06-16 09:31 UTC
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Forge

### Modloader Version

47.3.1

### Operating System

Windows

### List of all other installed mods

```
AdLods-1.20.1-8.1.2.0-build.0424.jar
ae2wtlib-15.2.3-forge.jar
agape_space-1.2.0.jar
alchemistry-1.20.1-2.3.4.jar
alchemylib-1.20.1-1.0.30.jar
alltheores-1.20.1-47.1.3-2.2.4.jar
amendments-1.20-1.2.4.jar
animal_feeding_trough-1.1.0+1.20.1-forge.jar
Apotheosis-1.20.1-7.3.5.jar
Apothic Amendments - Enchanting - 0.1.4.jar
ApothicAttributes-1.20.1-1.3.5.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.2.3.jar
architectury-9.2.14-forge.jar
avaritialite-forge-1.20.1-1.10.2.jar
balm-forge-1.20.1-7.3.4-all.jar
baubley-heart-canisters-1.20.1-1.0.5.jar
bedrockores-MC1.20.1-2.1.0+2b9c75d.jar
betterarcheology-1.1.9-1.20.1.jar
Beyond-Earth-1.20.1-7.0-PRERELEASE.jar
blockui-1.20.1-1.0.156-RELEASE.jar
bloodmagic-1.20.1-3.3.3-45.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
BuildingWands-mc1.20.1-2.6.9-release.jar
Capsule-1.20.1-8.0.105.jar
carryon-forge-1.20.1-2.1.2.7.jar
cataclysm_ut-7 - 1.20.1.jar
chemlib-1.20.1-2.0.19.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
CobbleForDays-1.8.0.jar
CodeChickenLib-1.20.1-4.4.0.512-universal.jar
cofh_core-1.20.1-11.0.2.56.jar
Collectibles-1.20.x-(v.1.4.8).jar
collective-1.20.1-7.61.jar
collectorsalbum-forge-1.20.1-1.5.5.jar
colorfulhearts-forge-1.20.1-4.1.8.jar
comforts-forge-6.3.5+1.20.1.jar
Compressium-3.0.2-build.12+mc1.20.jar
configuration-forge-1.20.1-2.2.1.jar
connectedglass-1.1.11-forge-mc1.20.1.jar
Connector-1.0.0-beta.43+1.20.1.jar
Corail-Spawners-1.20.1-035.jar
corail_pillar-1.20.1-5.9.1.jar
coroutil-forge-1.20.1-1.3.7.jar
craftingtweaks-forge-1.20.1-18.2.4.jar
crafts-1.0.0.jar
cupboard-1.20.1-2.6.jar
curios-forge-5.9.1+1.20.1.jar
customoreveins-1.20-1.0.0-forge.jar
Cyclic-1.20.1-1.12.9.jar
DarkUtilities-Forge-1.20.1-17.0.3.jar
day_counter v3.8 1.20.1 [FORGE].jar
dimdungeons-191-forge-1.20.1.jar
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal.jar
drg_flares-1.20-forge-1.2.8.jar
Electrodynamics-1.20.1-0.9.0-3.jar
elevatorid-1.20.1-lex-1.9.jar
embeddium-0.3.20+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.12.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.16.jar
EnderIO-1.20.1-6.0.25-alpha.jar
EnderStorage-1.20.1-2.11.0.188-universal.jar
ensorcellation-1.20.1-5.0.2.24.jar
entityculling-forge-1.6.6-mc1.20.1.jar
explorify-v1.4.0.jar
ExtraDisks-1.20.1-3.0.2.jar
fabric-api-0.92.2+1.11.8+1.20.1.jar
fastboot-1.20.x-1.1.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
flib-1.20.1-0.0.12.jar
ForgeEndertech-1.20.1-11.1.3.1-build.0496.jar
FramedBlocks-9.3.0.jar
ftb-chunks-forge-2001.3.1.jar
ftb-library-forge-2001.2.2.jar
ftb-teams-forge-2001.3.0.jar
fusion-1.1.1-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.4.6.jar
industrial-foregoing-1.20.1-3.5.17.jar
inventoryessentials-forge-1.20.1-8.2.6.jar
InventoryProfilesNext-forge-1.20-1.10.10.jar
itemcollectors-1.1.10-forge-mc1.20.jar
Jade-1.20.1-forge-11.9.2.jar
jei-1.20.1-forge-15.3.0.7.jar
justhammers-forge-2.0.3+mc1.20.1.jar
kotlinforforge-4.11.0-all.jar
libIPN-forge-1.20-4.0.2.jar
lionfishapi-1.9.jar
LiquidBlocks-1.20.1-2.0.1.jar
lootintegrationaddonyung-1.18-1.20.1-1.1.jar
lootintegrations-1.20.1-3.7.jar
lootr-forge-1.20-0.7.34.86.jar
L_Enders_Cataclysm-1.99.5 -1.20.1.jar
mcw-fences-1.1.1-mc1.20.1forge.jar
mcw-furniture-3.2.2-mc1.20.1forge.jar
mcw-holidays-1.1.0-mc1.20.1forge.jar
mcw-lights-1.0.6-mc1.20.1forge.jar
mcw-roofs-2.3.0-mc1.20.1forge.jar
mcw-windows-2.2.1-mc1.20.1forge.jar
minecolonies-1.20.1-1.1.563-RELEASE.jar
MineColonies_Compatibility-1.20.1-2.13.jar
MineColonies_Tweaks-1.20.1-2.21.jar
mobtimizations-forge-1.20.1-1.0.0.jar
Modern-Industrialization-1.8.5.jar.disabled
modernfix-forge-5.18.1+mc1.20.1.jar
moonlight-1.20-2.11.37-forge.jar
multipiston-1.20-1.2.43-RELEASE.jar
Nuclear_Science-1.20.1-0.6.0-2.jar
ore_dimensions-1.1.0.jar
pamhc2crops-1.20-1.0.3.jar
pamhc2foodcore-1.20.4-1.0.5.jar
pamhc2foodextended-1.20.4-1.0.1.jar
Patchouli-1.20.1-84-FORGE.jar
Pehkui-3.8.2+1.20.1-forge.jar
perfectplushies-forge-1.20.1-1.9.0.jar
PigPen-Forge-1.20.1-15.0.2.jar
Placebo-1.20.1-8.6.2.jar
pneumaticcraft-repressurized-6.0.15+mc1.20.1.jar
polymorph-forge-0.49.5+1.20.1.jar
Powah-5.0.5.jar
ProjectE-1.20.1-PE1.0.1.jar
ProjectE_Integration-1.20.1-7.2.2.jar
PuzzlesLib-v8.1.20-1.20.1-Forge.jar
rangedpumps-1.1.0.jar
refinedstorage-1.12.4.jar
regionaloreveins-1.20.1-1.0.0.jar
Runelic-Forge-1.20.1-18.0.2.jar
Satako-7.0.16-1.20.1.jar
seasonhud-forge-1.20.1-1.8.6.jar
SereneSeasons-1.20.1-9.0.0.46.jar
sereneseasonsphc2crops-1.20.1-1.0.0.jar
SimplyHouses-1.1.4-1.20.1-forge.jar
simplylight-1.20.1-1.4.6-build.50.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
stackrefill-1.20.1-4.4.jar
structurize-1.20.1-1.0.733-RELEASE.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.15.jar
svmm-1.20.1-1.3.0.3.jar
tarotcards-1.0.0-forge-1.20.1.jar
tarotcards-1.20-1.6.3.jar
theoneprobe-1.20.1-10.0.2.jar
time-in-a-bottle-4.0.4-mc1.20.1.jar
tinypipes-1.20-4.0.0.jar
titanium-1.20.1-3.8.28.jar
torchmaster-20.1.6.jar
towntalk-1.20.1-1.1.0.jar
Trading Table-3.0.0-1.20.1.jar
TradingPost-v8.0.2-1.20.1-Forge.jar
TrampleStopper-Forge-5.0.0+mc1.20.1.jar
trashslot-forge-1.20-15.1.0.jar
TreeChop-1.20.1-forge-0.19.0.jar
trenzalore-forge-3.3.10+mc1.20.1-all.jar
valkyrielib-forge-1.20.1-4.0.4.0.jar
voidminer-1.1.0.jar
water_sources_1.20.1_1.0.0.jar
waystones-forge-1.20-14.1.3.jar
XaerosWorldMap_1.38.8_Forge_1.20.jar
Xaeros_Minimap_24.2.0_Forge_1.20.jar
xaeros_waystones_compability-1.0.jar
YungsApi-1.20-Forge-4.0.5.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
YungsMenuTweaks-1.20.1-Forge-1.0.2.jar
```

### Describe the problem

![Immagine](https://github.com/blackd/Inventory-Profiles/assets/63145139/d77acf6e-47aa-49b4-ae11-24dd4a135284)

### Steps to reproduce

The issue seems appear with Apotheosis gems and other objects are into inventory (check the image)

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment] 2024-06-16 09:35
Duplicate of #356

**Closed as not planned** 2024-06-16 09:35 UTC
