### ISSUE TITLE
Sort Inventory doesn't work with two of same type of map

### ISSUE THREAD

**Issue by ChivalKnight** [blackd/Inventory-Profiles#415] opened 2024-06-21 03:36 UTC
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21

### Modloader

Fabric

### Modloader Version

Fabric-loader-0.15.11-1.21

### Operating System

Windows

### List of all other installed mods

![MyMinecraftMods](https://github.com/blackd/Inventory-Profiles/assets/105532842/fe506c9f-f52f-4eaf-8da3-7b8a04ee16ef)

### Describe the problem

Note: This is singleplayer.
Chests will not sort with two maps (these were obtained from two different cartographers, maps called Ocean Explorer Map with IDs #6 and #7) 
It also puts one Java error into chat every time I click on any sort buttons, including with different sorting methods.
I have no logs because the game does not crash and I'm unsure how to get logs otherwise...

The error it throws in chat is as follows: 

java.lang.ClassCastException: class net.minecraft.class_9209 cannot be cast to class net.minecraft.class_9295 (net.minecraft.class_9209 and net.minecraft.class_9295 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader@69b794e2)

![2024-06-20_20 09 12](https://github.com/blackd/Inventory-Profiles/assets/105532842/be7c9748-1d67-4841-acb4-3fe4eab92057)

### Steps to reproduce

1) Put two maps of the same type (For example, two Ocean Explorer or two Trial Explorer) in from the cartographers (I'm not sure if it happens with other maps)
2) Try to sort 

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment] 2024-06-21 03:38
Duplicate of #412

**Closed as not planned** 2024-06-21 03:39 UTC
