### ISSUE TITLE
Incompatible with Forge 1.17.1 37.0.67

### ISSUE THREAD

**Issue by Kylous7** [blackd/Inventory-Profiles#49] opened 2021-09-18 16:08 UTC

**Comment by blackd** [comment] 2021-09-18 20:44
could you elaborate?

**Comment by blackd** [comment] 2021-09-18 20:45
and include the version of the mod

**Comment by Kylous7** [comment] 2021-09-18 23:22
Version: InventoryProfilesNext-forge-1.17-1.0.2.jar

Error:
Forge: net.minecraftforge:37.0.67[00:20:58] [main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Inventory Profiles Next (inventoryprofilesnext) has failed to load correctly
º7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:236) ~[fmlcore-1.17.1-37.0.67.jar%2333!:?]
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.67.jar%2333!:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.67.jar%2333!:?]
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.67.jar%2333!:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.67.jar%2333!:?]
        at net.minecraftforge.fmllegacy.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge-1.17.1-37.0.67-universal.jar%2336!:?]
        at net.minecraft.server.Main.main(Main.java:100) ~[server-1.17.1-20210706.113038-srg.jar%2332!:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.67.jar%2322!:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]

**Comment by blackd** [comment] 2021-09-19 00:26
this mod is pure client side only and you don't need to have it on the server.

**Comment by Kylous7** [comment] 2021-09-19 16:44
If i add only on client it gives that 0 error

**Comment by Kylous7** [comment] 2021-09-19 16:46
so that's why i tried on the sv

**Comment by blackd** [comment] 2021-09-19 16:52
I can't reproduce it here

can you please explain what "that 0 error" mean

**Comment by Kylous7** [comment] 2021-09-20 13:02
I have seen it in a lot of threads, i thought you would have seen it but
[https://ibb.co/HLZpDBj](url)
Sorry it's in Portuguese but easy to understand

**Comment by blackd** [comment] 2021-09-20 13:25
Can you please try to start the game and upload this file %appdata%\.minecraft\logs\latest.log

**Comment by blackd** [comment] 2021-10-22 06:35
this issue will soon be closed due to inactivity

**Comment by ZeroDragon** [comment] 2021-10-22 16:45
FWIW:
I had the same problem on my client, installed the mod from forge release page, but from there it only downloads the fabric version.
However downloading (the forge version) from github releases it works just perfect

**Comment by blackd** [comment] 2021-10-22 17:37
which versions?

**Comment by ZeroDragon** [comment] 2021-10-22 20:04
tested it with
MC 1.17.1
Forge 37.0.95
Inventory profiles (fabric version with fabric loader) v1.1.1

Thing is, when you get to courseforge (and tlauncher mods) it always downloads the fabric version.
![image](https://user-images.githubusercontent.com/616185/138515887-156a0485-48a9-4753-9ece-16f0e3a44945.png)
![image](https://user-images.githubusercontent.com/616185/138515914-056d68de-608b-4811-8bb4-2a3fa411755f.png)

Error in game is literally "this mod is for fabric version and cannot run in forge"

But once using the correct (forge) version it works fine
Inventory profiles (forge edition) v1.1.1

**Comment by blackd** [comment] 2021-10-23 09:44
Unfortunately this is how curseforge works. To be sure that you download the right file it's better to click on "Files" and then choose the one for your loader and game version.

**Comment by ZeroDragon** [comment] 2021-10-23 13:42
I think that's what happened to OP, probably if OP is no longer answering it's safe to close the issue
I just wanted to show some extra light on this. Because I came to this issue with the same problem, then started looking at your release files.

Thanks for this mod!!

**Closed as completed** 2021-10-24 09:08 UTC
Labels: invalid
