### ISSUE TITLE
Possible Incompatability with Just Enough Items Addon Just Enough Professions

### ISSUE THREAD

**Issue by Oxeus** [blackd/Inventory-Profiles#359] opened 2023-09-14 00:34 UTC
### Have you asked for help on discord?

YES

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

Fabric 0.14.22
Also tested Quilt 0.20.2 to see if issue also occurred but all testing was on fabric

### Operating System

Windows

### List of all other installed mods

AppleSkin - FBR.jar
AutoFish - FBR.jar
Better Advancements - FBR.jar
BetterF3 - FBR.jar
Catalogue - FBR.jar
Cloth-Config - FBR.jar
Connectivity - FBR.jar
Continuity - FBR.jar
Controlling - FBR.jar
Craftify - FBR.jar
Debugify - FBR.jar
EnchantmentDescriptions - FBR.jar
Enhanced Block Entities - FBR.jar
FerriteCore - FBR.jar
ImmediatelyFast - FBR.jar
InventoryProfilesNext - FBR.jar
InvHud+ - FBR.jar
Iris - FBR.jar
Jade - FBR.jar
JEI - FBR.jar
JEI - JEP - FBR
JMI - FBR.jar
JourneyMap - FBR.jar
Lib - Architectury - FBR.jar
Lib - Bookshelf - FBR.jar
Lib - Cupboard - FBR.jar
Lib - Fabric API - FBR.jar
Lib - IPN - FBR.jar
Lib - Konkrete - FBR.jar
Lib - Kotlin - FBR.jar
Lib - Malilib - FBR.jar
Lib - Searchables - FBR.jar
Sodium - Extra - FBR.jar
Sodium - FBR.jar
Sodium - Reese's Options - FBR.jar
Sodium - Sodium - FBR.jar

![Screenshot 2023-09-13 170335](https://github.com/blackd/Inventory-Profiles/assets/13008923/f8f61725-a692-464c-9760-52c9c55e2510)

### Describe the problem

1. It seems there is an issue with compatibility for Just Enough Items addon Just Enough Professions, the game runs fine but the config does not save. I delete the config on a test world and enter the world. I then bookmark on a villager, and it does not save to the config. I have taken out the mod addon for JEI and the config saving works, and when I put it back it stops saving. Maybe this is a possible incompatibility.

2. No Screenshots ingame. The game does not save config file.

4. Single player and on an SMP running Purpur I am on, tested also on my paper server.

Logs Searchable: https://mclo.gs/VMQUeop

Text File: [ipn-log.txt](https://github.com/blackd/Inventory-Profiles/files/12602691/ipn-log.txt)

### Steps to reproduce

1. If Just Enough Items Just Enough Professions installed then Load into World, change bookmarks on a villager to update save files for trades.
2. Save Game.
3. Check config folder for IPN no updated save data file for current world.
4. Close Game and remove said addon.
5. Delete save for villager trading of world.
6. Load into world to test and proceed to bookmark trade.
7. Check save data in config folder for IPN.
8. Save data should be updated when JEP not installed.

On my computer and mod setup these steps produced no save data for villager trades.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment] 2023-11-11 15:40
Looks like this is caused by journey map.
the issue has been reported and will be fixed in future journey map release

**Closed as completed by blackd** 2023-11-11 15:40 UTC
