### ISSUE TITLE
Dupe glitch with stonecutter

### ISSUE THREAD

**Issue by Flajekt** [blackd/Inventory-Profiles#257] opened 2022-12-23 18:25 UTC
I better let you see what happened. Here is the link to the video https://youtu.be/Y_o4O_GCeZA

**Comment by blackd** [comment] 2022-12-23 18:33
what kind of server is this

**Comment by Flajekt** [comment] 2022-12-23 18:34
> what kind of server is this
This is single player

**Comment by blackd** [comment] 2022-12-23 18:37
So I can't reproduce it.

What other mods do you have?

**Comment by Flajekt** [comment] 2022-12-23 18:47
> So I can't reproduce it.
> 
> What other mods do you have?

SOoh, too much I think

I don't use global mods
Only vanila +

appleskin-fabric-mc1.19-2.4.1
BetterF3-4.0.0-Fabric-1.19.2
betterfpsdist-fabric-1.19.1-2.0
bobby-4.0.1
CITResewn-1.1.2+1.19.2
clickthrough-1.19.1-fabric0.58.5-0.4
cloth-config-8.2.88-fabric
continuity-2.0.1+1.19
CreativeCore_FABRIC_v2.9.3_mc1.19.2
DripSounds-1.19-0.3.0
dynamic-fps-2.2.0
dynamic-music-1.5.1
effective-1.6+1.19.2
extrasounds-2.3.1+1.19.2-1.19.1
fabric-language-kotlin-1.8.7+kotlin.1.7.22
fallingleaves-1.13.0+1.19.2
illuminations-1.10.11
indium-1.0.9+mc1.19.2
iris-mc1.19.2-1.4.3
item-model-fix-1.0.3+1.19
ItemPhysic_FABRIC_v1.6.6_mc1.19.2
lazydfu-0.1.3
libIPN-fabric-1.19-1.0.7
litematica-fabric-1.19.2-0.12.5
lithium-fabric-mc1.19.2-0.10.2
lmd-1.19.2-1.0-bukkit-paper
malilib-fabric-1.19.2-0.13.0
modmenu-4.1.1
phosphor-fabric-mc1.19.x-0.8.1
PresenceFootsteps-1.6.3
qfapi-4.0.0-beta.23_qsl-3.0.0-beta.22_fapi-0.68.0_mc-1.19.2
reeses_sodium_options-1.4.7+mc1.19.2-build.59
replaymod-1.19.2-2.6.10
shulkerboxtooltip-fabric-3.2.2+1.19.2
sodium-extra-0.4.9+mc1.19.2-build.60
sodium-fabric-mc1.19.2-0.4.4+build.18
soundphysics-fabric-1.19.2-1.0.15
visuality-0.5.5

**Comment by Flajekt** [comment] 2022-12-23 18:49
> So I can't reproduce it.
> 
> What other mods do you have?

I don't use global mods
Only vanila +

**Comment by blackd** [comment] 2022-12-24 06:38
I can't recreate this on fabric. And Quilt is "supported" as long as it doesn't require special efforts.   

[shronecutter.webm](https://user-images.githubusercontent.com/333840/209424642-870e7d19-648d-4d46-b8a4-996c77b25663.webm)

**Comment by blackd** [comment] 2022-12-24 06:47
also judging by libIPN version you are few versions behind.
does it still happen with the latest version.

**Comment by blackd** [comment] 2022-12-24 07:08
this is quilt specific and it appears to be fixed in qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar

**Closed as not planned by blackd** 2022-12-24 07:08 UTC
Labels: invalid, wontfix

**Comment by Flajekt** [comment] 2022-12-24 11:46
I have installed the new version of qfapi and libIPN and the dupe glitch was fixed. 
Thank you so much! And thank you for wasting your time on me!
