### ISSUE TITLE
Crash while starting the game

### ISSUE THREAD

**Issue by Dr-WeiAL** [blackd/Inventory-Profiles#39] opened 2021-08-10 13:39 UTC
Did it conflict with which mod and cause the crash?
[latest.log](https://github.com/blackd/Inventory-Profiles/files/6962084/latest.log)
[debug.log](https://github.com/blackd/Inventory-Profiles/files/6962085/debug.log)

**Comment by blackd** [comment] 2021-08-10 13:47
Hi,
Can you attach a list with all installed mods

**Comment by Dr-WeiAL** [comment] 2021-08-10 14:01
It’s a bit too much, it took some time
[mods.txt](https://github.com/blackd/Inventory-Profiles/files/6962236/mods.txt)

**Comment by marie-bnl** [comment] 2021-08-10 14:25
To make sure it's a conflict with another mod, I guess it doesn't crash when using only Inventory Profiles?

**Comment by marie-bnl** [comment] 2021-08-10 14:27
So I read the log, and for me it could be a conflict with Placebo

**Comment by Dr-WeiAL** [comment] 2021-08-10 14:35
> So I read the log, and for me it could be a conflict with Placebo

Uh... but after blocking Placebo and all mods that use it as a front end, it still crashes

**Comment by marie-bnl** [comment] 2021-08-10 14:37
Could you send the log after it crashes without Placebo?

**Comment by Dr-WeiAL** [comment] 2021-08-10 14:39
> Could you send the log after it crashes without Placebo?

okay
[latest.log](https://github.com/blackd/Inventory-Profiles/files/6962512/latest.log)

**Comment by marie-bnl** [comment] 2021-08-10 14:44
I guess you use a modpack? If so, which? I'd like to install all the mods to be able to test a bit

**Comment by Dr-WeiAL** [comment] 2021-08-10 14:46
> I guess you use a modpack? If so, which? I'd like to install all the mods to be able to test a bit

This is a modpack I made by myself, and I didn’t upload it, do you want me to upload it to github?

**Comment by blackd** [comment] 2021-08-10 14:48
it will help if you can upload it

**Comment by Dr-WeiAL** [comment] 2021-08-10 14:54
> it will help if you can upload it

Uh, I am in China, and modpack is too big, github does not allow me to upload, can you open pan.baidu.com? I upload it inside if possible

**Comment by blackd** [comment] 2021-08-10 14:56
Don't worry I'll download them all by hand.

**Comment by marie-bnl** [comment] 2021-08-10 14:58
Personally I can open baidu if you want to upload them anyway

**Comment by Dr-WeiAL** [comment] 2021-08-10 14:59
> Don't worry I'll download them all by hand.



> Personally I can open baidu if you want to upload them anyway

https://pan.baidu.com/s/1n5Y754QcxBCK9f1d-tQvDg
Extraction code: 3765

**Comment by marie-bnl** [comment] 2021-08-10 15:00
Thanks!

**Comment by Dr-WeiAL** [comment] 2021-08-10 15:04
> Thanks!

It’s okay, as long as these things can help you, but I forgot to delete a mod, you have to delete i18nupdatemod, otherwise you will be in Chinese after startup

**Comment by blackd** [comment] 2021-08-10 15:52
what loader do you use? CurceForge MultiMC ATLauncher Vanilla

does it support exporting a modpack? I know that ATLauncher and MultiMC support exporting if you can just export it in Curceforge format?

**Comment by marie-bnl** [comment] 2021-08-10 15:52
I tried to download it but I get a ton of errors and the website is very slow for me, could you upload it on  
https://www.swisstransfer.com/fr  
please? Thanks!

**Comment by Dr-WeiAL** [comment] 2021-08-10 15:58
> I tried to download it but I get a ton of errors and the website is very slow for me, could you upload it on
> https://www.swisstransfer.com/fr
> please? Thanks!

I don't know how to use this website, and it's very slow, can you provide your email address? I want to try if I can send the file by email

**Comment by marie-bnl** [comment] 2021-08-10 15:59
victor.bonnelle@protonmail.com

**Comment by Dr-WeiAL** [comment] 2021-08-10 16:01
> what loader do you use? CurceForge MultiMC ATLauncher Vanilla
> 
> does it support exporting a modpack? I know that ATLauncher and MultiMC support exporting if you can just export it in Curceforge format?

I am using this 
https://hmcl.huangyuhui.net/

I can export as MultiMC can use
Do you want to send it to your mailbox like him?

**Comment by Dr-WeiAL** [comment] 2021-08-10 16:05
> [victor.bonnelle@protonmail.com](mailto:victor.bonnelle@protonmail.com)

I have sent it, hope you can receive the mail over there

**Comment by marie-bnl** [comment] 2021-08-10 16:13
I have it!

**Comment by marie-bnl** [comment] 2021-08-10 16:15
https://www.swisstransfer.com/d/74671586-443e-48c2-b1b0-934991ab6b9f

**Comment by marie-bnl** [comment] 2021-08-10 16:25
I can reproduce it

**Comment by Dr-WeiAL** [comment] 2021-08-10 16:30
> I can reproduce it

I use this website to download very fast, but I don’t know about uploading. In addition, did you find the problem?

**Comment by marie-bnl** [comment] 2021-08-10 16:30
I'm doing some tests

**Comment by Dr-WeiAL** [comment] 2021-08-10 16:33
> I'm doing some tests

Okay, thanks for your hard work, but it's early morning on my side, it's almost time to go to bed, I may not get the news in a while

**Comment by marie-bnl** [comment] 2021-08-10 16:34
Of course of course, good night!

**Comment by marie-bnl** [comment] 2021-08-10 16:57
The mod that causes the conflict seems to be `timeless_and_classic_4.0.0_RELEASE.jar`

EDIT: removing only timeless doesn't fix it so I think timeless is just one of the conflicts

**Comment by Dr-WeiAL** [comment] 2021-08-10 17:09
> The mod that causes the conflict seems to be `timeless_and_classic_4.0.0_RELEASE.jar`
> 
> EDIT: removing only timeless doesn't fix it so I think timeless is just one of the conflicts

It’s too much trouble to use github, let me talk to you directly with discord

**Comment by marie-bnl** [comment] 2021-08-10 17:23
After talking a bit on Discord, the two mods causing the conflict seem to be `timeless_and_classic_4.0.0_RELEASE.jar` and `i18nupdatemod-1.16.5-2.0.2-hotfix-4.jar`. We're now looking for the exact problem

**Comment by blackd** [comment] 2021-08-11 08:07
Both of above are core mods and change minecraft directly. This makes very hard to have MixIns due to unexpected changes in the core classes interface.
It's up to the core mods not to break the interface

**Comment by blackd** [comment] 2021-08-11 12:15
The problem has been pinpointed to over-zealous mixin configuration
```json
  "injectors": {
    "defaultRequire": 1
  }
```

**Comment by blackd** [comment] 2021-08-11 13:28
After further investigation removing the above section fixes the crash. BUT the mixin is still not attached,

However I found that both i18n.. and timeless.. have .mixins.json files that don't really point to mixins removing them allows the game to start and out mixins to attach.

Closing and marking as invalid again since the problem is most probably caused by the empty mixins.json files

**Closed as completed by blackd** 2021-08-11 13:28 UTC
Labels: invalid

**Comment by baka-gourd** [comment] 2021-08-11 13:51
> After further investigation removing the above section fixes the crash. BUT the mixin is still not attached,
> 
> However I found that both i18n.. and timeless.. have .mixins.json files that don't really point to mixins removing them allows the game to start and out mixins to attach.
> 
> Closing and marking as invalid again since the problem is most probably caused by the empty mixins.json files

BUT the mixin is still not attached,
According to the picture, I think it attached.
How can I make it not attached?

edited: got it, it is truely.

**Comment by blackd** [comment] 2021-08-11 13:55
The mod starts yes however the part that the mixin handles doesn't work.

one of the mixins disables shift move/ctrl+q of items in locked slots. if I just remove the above section the crash is gone but the player can still use ctrl+q to throw stuff out of locked slots

**Comment by blackd** [comment] 2021-08-11 20:15
I still think this is not this or the other mods problem but after more investigating and some talking with people from forge THE MAIN REASON IS that  all mods have mixin.refmap.json filet their jars. And for some reason when IPN mixins are processed some of the other mixin.refmap.json files is loaded instead of the one in IPN. 

So I will make the file name unique to avoid further problems related to that.
