### ISSUE TITLE
Ability to lock certan items/item types in place in inventory and hotbar

### ISSUE THREAD

**Issue by Mackzwellz** [blackd/Inventory-Profiles#24] opened 2021-07-15 21:12 UTC
Please see https://github.com/kyrptonaught/Inventory-Sorter/issues/33 for complete proposal.
I can copy it over here if needed.

**Comment by blackd** [comment] 2021-07-16 05:30
As with picking items in empty locked slots this will require server side support. Or it can be implemented for single player only.
If we go the server side route everything will have to be reimplemented.

Let me explain. Sorting for example is now implemented to simulate clicks that move items around the inventory that way the mod, at least most of it, works on any type of server. However when it comes to picking up items the server just informs the client you now have these items in your inventory. So any functionality that changes the behaviour of item pickup process will have to be handled server side. 
While investigating #13 I've discovered that to support it I'll have to:
- implement server client handshake so we know if we are working with supported server or not
- move the configuration server side or make it so the client uploads it every time it connected.
- maintain the local configuration for servers that don't have the mod
- move the sorting server side so it's atomic and doesn't clash with item pickups (see #22 it's more likely to occur when connected to servers)
- to keep the current set of features I need to maintain 2 types of sorting clients side and server side on the surface it sound that probably most of the code can be reused but see [this](https://github.com/blackd/Inventory-Profiles/issues/15#issuecomment-873553079)
- implement a protocol between the client and the server that handles all of the above

Implementing your suggestion will require all of the above and I suspect more.

And I'm reluctant to go the server side route because it looks like people use the mod variety of servers. 

As with #13 it look that may be it's possible to handle this with some complex logic that does it client side so I'll keep this open.

**Comment by Mackzwellz** [comment] 2021-07-16 20:15
@blackd thank you for the detailed explanation.

I personally play on mostly vanilla servers with modded fabric client, so I would prefer the client-side handling of this very much.
I think the possible middle ground is NOT to sort on pickup, but add the ability for user to sort it via hotkey manually. It does not have to be instant/very fast as well (since we are working around server-side limitations and all that). But I would take ability to have items at the right places in hotbar at the push of a single button over not having any kind of auto-sorting ability any day.

Hopefully both this and #13 can be solved this way at some point. And thank you for maintaining the mod as well!

**Comment by blackd** [comment] 2021-07-18 09:48
@Mackzwellz I investigated the code and by the looks of it the "profiles" part of the name was intended for exactly keeping the hotbar and equipment slots in a specified state depending on the selected profile. However this was never implemented by the original author. So yeah it will take some time but I'll probably implement it.

**Comment by blackd** [comment] 2021-08-08 13:33
So from the original request ONLY the part about hotbar and player equipment (offhand and armour slots ) is accepted. Locked slots can be used to achieve some parts of the request for the inventory.

Next version will contain profiles support but without easy way to manage them in game.

**Comment by blackd** [comment] 2021-08-20 06:16
will be released in v0.9.0 or probably v1.0.0

**Closed as completed by blackd** 2021-08-20 06:16 UTC
Labels: mod feature request
