### ISSUE TITLE
Incompatible with "Stacker" mod?

### ISSUE THREAD

**Issue by Wubzzz1337** [blackd/Inventory-Profiles#293] opened 2023-02-28 16:49 UTC
It seems that if items are more than 64 per stack the sorting system doesn't work that well/correctly.

Mod Used: https://www.curseforge.com/minecraft/mc-mods/stacker

"Inventory Sorting" is working fine tho: https://www.curseforge.com/minecraft/mc-mods/inventory-sorting

**Comment by blackd** [comment] 2023-02-28 16:58
Duplicate of https://github.com/blackd/Inventory-Profiles/issues/169

this is already reported to Stacker but they haven't reacted on it yet
https://github.com/Andrew6rant/Stacker/issues/65

As IPN is client side, the client should be informed about the size of the stacks by the server.  

There is a workaround you need to start single player game with the expected stack size and then connect to the server. 

"inventory sorting" is server side and doesn't depend on the client to be properly configured to handle the oversized stacks

**Comment by Wubzzz1337** [comment] 2023-02-28 17:28
Thanks for the info will use the workaround for now but hope u can fix this somehow soonish <3
Dont wanna use 2 mods for the same thing as I do right now x)

**Comment by blackd** [comment] 2023-02-28 17:29
I can't fix this
ask stacker devs

**Comment by blackd** [comment] 2023-03-06 13:43
duplicate of https://github.com/blackd/Inventory-Profiles/issues/169

in my opinion Stacker should update the client stack sizes when the client connects to a server

**Closed as not planned** 2023-03-06 13:43 UTC

**Comment by Wubzzz1337** [comment] 2023-03-06 13:56
True, I hope he answers/sees the Issue on his GitHub :(

**Comment by Wubzzz1337** [comment] 2023-03-24 15:53
Seems like he aint fixing anything :(

**Comment by blackd** [comment] 2023-03-24 17:08
I'm not sure if I can do anything about this

**Comment by Andrew6rant** [comment] 2023-03-24 22:09
Yeah, this is on me to fix. Stacker's whole system wasn't built for dedicated servers (whoops!), and I do not have the time right now to rewrite it to function properly. In the future I will, but it will not happen for a while.
