### ISSUE TITLE
Feature request: auto sort

### ISSUE THREAD

**Issue by marie-bnl** [blackd/Inventory-Profiles#32] opened 2021-07-31 23:23 UTC
A great feature would be to automatically sort the chest/inventory on some events like

- Open
- Modify (put, remove or move items)
- Close

To always keep my chests sorted without breaking my R key

**Comment by blackd** [comment] 2021-07-31 23:26
Duplicate of #23.

Long story short.. it breaks things like stack management.

**Closed as completed by blackd** 2021-07-31 23:26 UTC
Labels: wontfix

**Comment by marie-bnl** [comment] 2021-07-31 23:52
Ooops sorry I didn't see #23, thanks for your answer anyway
