### ISSUE TITLE
Possible compatibility with https://www.curseforge.com/minecraft/mc-mods/tokenable-furnaces-and-storage and https://www.curseforge.com/minecraft/mc-mods/stacker

### ISSUE THREAD

**Issue by 2el222** [blackd/Inventory-Profiles#169] opened 2022-08-09 17:24 UTC
Inventory profiles cant sort chests with these mods...

**Comment by blackd** [comment] 2022-08-09 17:26
describe the problem

video will be nice

**Comment by 2el222** [comment] 2022-08-09 19:56
Well, if u make an tokenable chest and have an increased stack size, lets say we have 256, it wont sort, try making amethyst chest, fill up more than one page and try to sort it, it wont sort, or will sort in a very messy way

**Comment by blackd** [comment] 2022-08-09 20:03
unfortunately oversized stacks are not supported
because they don't fallow the vanilla click rules
at this point IPN tryes to "support" such stacks by ignoring them

**Comment by QZLin** [comment] 2022-09-10 08:34
Found something funny, I use Stacker (Andrew6rant/Stacker) and Inventory-Profiles on Minecraft fabric 1.19.1. 
Sort function will not work for oversized stacks if I directly join a multiplayer game. But if I leave the multiplayer game then open a local world and close it, sorting will work on both the local world and multiplayer world (for oversized stacks).
Hope this information will help with Stacker compatibility.

**Comment by blackd** [comment] 2022-09-10 10:14
Looks like the problem is caused by Stacker because because ItemStack::getMaxCount returns 64 when connected to a server. IPN uses this value to check if the stack is oversized.

![изображение](https://user-images.githubusercontent.com/333840/189478784-cb83ca4d-1497-45fc-a46a-2dab5a8e235d.png)

I suggest you report this to Stacker.

**Closed as not planned** 2022-11-06 09:32 UTC
